--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec: 
  replicas: 1
  selector: 
    app: k8s-bigip-ctlr-deployment
    matchLabels: ~
  template: 
    imagePullSecrets: 
      - 
        name: bigip-login
    metadata: 
      labels: 
        app: k8s-bigip-ctlr-deployment
    spec: 
      containers: 
        - 
          args: 
            - "--bigip-username=$(BIGIP_USERNAME)"
            - "--bigip-password=$(BIGIP_PASSWORD)"
            - "--bigip-url=http://10.1.1.12:8443"
            - "--bigip-partition=ocp"
            - "--pool-member-type=nodeport"
            - "--insecure"
          command: 
            - /app/bin/k8s-bigip-ctlr
          env: 
            - 
              name: BIGIP_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: bigip-login
            - 
              name: BIGIP_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: bigip-login
          image: f5networks/k8s-bigip-ctlr
          name: k8s-bigip-ctlr
      serviceAccount: bigip-ctlr
      serviceAccountName: bigip-ctlr